# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=32, verbose_name='ticket')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Login Ticket',
                'verbose_name_plural': 'Login Tickets',
            },
        ),
        migrations.CreateModel(
            name='ProxyGrantingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=32, verbose_name='ticket')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('pgtiou', models.CharField(max_length=256, verbose_name='PGTiou')),
            ],
            options={
                'verbose_name': 'Proxy Granting Ticket',
                'verbose_name_plural': 'Proxy Granting Tickets',
            },
        ),
        migrations.CreateModel(
            name='ProxyGrantingTicketIOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=32, verbose_name='ticket')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('proxyGrantingTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cas_provider.ProxyGrantingTicket', verbose_name='Proxy Granting Ticket')),
            ],
            options={
                'verbose_name': 'Proxy Granting Ticket IOU',
                'verbose_name_plural': 'Proxy Granting Tickets IOU',
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=32, verbose_name='ticket')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('service', models.URLField(max_length=500, verbose_name='service')),
            ],
            options={
                'verbose_name': 'Service Ticket',
                'verbose_name_plural': 'Service Tickets',
            },
        ),
        migrations.CreateModel(
            name='ProxyTicket',
            fields=[
                ('serviceticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cas_provider.ServiceTicket')),
            ],
            options={
                'verbose_name': 'Proxy Ticket',
                'verbose_name_plural': 'Proxy Tickets',
            },
            bases=('cas_provider.serviceticket',),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='proxygrantingticket',
            name='serviceTicket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cas_provider.ServiceTicket'),
        ),
        migrations.AddField(
            model_name='proxyticket',
            name='proxyGrantingTicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cas_provider.ProxyGrantingTicket', verbose_name='Proxy Granting Ticket'),
        ),
    ]
